# Generated by Django 5.1.1 on 2024-09-26 12:30

import todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["deadLine"]},
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadLine",
            field=models.DateField(
                default=todos.models.timezone.now, verbose_name="Data de Entrega"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(
                blank=True, default=todos.models.timezone.now, null=True
            ),
        ),
    ]
